server:
  contextPath:
  port: 9080

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null

auth:
  header: auth-token